# Generated by Django 3.1.5 on 2021-01-28 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbsApp', '0003_auto_20210128_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 2, 9, 50, 608512, tzinfo=utc)),
        ),
    ]
