--DDL(CREATE, DROP, ALTER)
-- 1.TABLE 생성(제약조건)
--CREATE  TABLE TABLE_NAME(
--    COLUM_NAME DATETYPE [DEFAULT EXPR][CONSTRAINT],
--    COLUM_NAME DATETYPE [DEFAULT EXPR][CONSTRAINT],
--    COLUM_NAME DATETYPE [DEFAULT EXPR][CONSTRAINT],
--    TABLE_CONSTRAINT
--)
--INSERT 구문
--INSERT INTO    TABLE_NAME[(컬럼리스트)] VALUES(VALUE, VALUE);

--CREATE
CREATE  TABLE TEST_MENBER(
    ID      VARCHAR2(50),
    PW      VARCHAR2(50) NOT NULL,
    ADDR    VARCHAR2(50) DEFAULT 'SEOUL',
    PRIMARY KEY(ID, PW) --두개의 제약조건은 테아블레벨에서만 가능
);

--INSERT
INSERT  INTO TEST_MENBER(ID, PW, ADDR) VALUES('RUBY', 'RUBY', 'SEOUL');
INSERT  INTO TEST_MENBER(ID, PW, ADDR) VALUES('RUBY', 'ADMIN', 'SEOUL');--TABLE의 제약조건으로 인해 (ID,PW)를 하나로 인식
--INSERT  INTO TEST_MENBER(ID, PW, ADDR) VALUES('ruby', null, null); --PW의 제약조건이 NOT NULL이므로 오류발생
INSERT  INTO TEST_MENBER(ID, PW) VALUES('ADMIN', 'ADMINPW'); --ADDR의 제약조건이 DEFAULT SEOUL이므로 ADDR의 빈 곳에 자동으로 입력

--SELECT
SELECT  *
FROM    TEST_MENBER;

--DROP
DROP    TABLE TEST_MENBER;

--2.제약조건 : NOT NULL(컬럼레벨 제약만 가능!), UNIQUE, PRIMARY KEY, FOREIGEN KEY, CHECK
--2-1.제약조건 설정밥법 : 테이블레벨, 컬럼레벨

--FK : 부모에 의존하는 데이터이거나 NULL값을 허용
--부모를 참조하는 외래키 만들기(컬럼레벨)
CREATE TABLE TABLE_FK(
    ID      CHAR(3) PRIMARY KEY,
    NAME    VARCHAR(50) NOT NULL,
    LID     CHAR(2) REFERENCES LOCATION(LOCATION_ID),
    
);

--부모를 참조하는 외래키 만들기(테이블레벨)
CREATE TABLE TABLE_FK(
    ID      CHAR(3) PRIMARY KEY,
    NAME    VARCHAR(50) NOT NULL,
    LID     CHAR(2),
    FOREIGN KEY(LID) REFERENCES LOCATION (LOCATION_ID)
);

INSERT INTO TABLE_FK VALUES('A', 'RUBY', 'A1');
INSERT INTO TABLE_FK VALUES('B', 'DIA', 'OT');
INSERT INTO TABLE_FK VALUES('C', 'DIA', NULL);
--INSERT INTO TABLE_FK VALUES('A', 'RUBY', 'X') --부모키에 X가 없으므로 오류

SELECT  *
FROM    TABLE_FK;

DROP TABLE TABLE_FK;

--만들어진 테이블에 JOIN
SELECT  LOC_DESCRIBE, ID
FROM    LOCATION L
JOIN    TEST_FK T ON(L.LOCATION_ID = T.LID);

SELECT  *
FROM    LOCATION;

--한개의 부모테이블을 갖는 자식테이블
CREATE TABLE    TEST_COMPOSIT_PK(
    ID      VARCHAR2(50),
    NAME    VARCHAR2(50),
    SALARY  NUMBER  CHECK(SALARY > 0),
    GENDER  CHAR(1) CHECK(GENDER IN('M', 'F')),
    PRIMARY KEY(ID, NAME)
);

--INSERT INTO TEST_COMPOSIT_PK VALUES('RUBY', '녕', -100, 'F'); --CHECK제약조건에 SALARY > 0 이므로 오류
INSERT INTO TEST_COMPOSIT_PK VALUES('RUBY', '녕', 100, 'F');

SELECT  *
FROM    TEST_COMPOSIT_PK;

DROP TABLE  TEST_COMPOSIT_PK;

-----------------------------------------------------------------
CREATE TABLE    TEST_COMPOSIT_FK(
    PID     VARCHAR2(50),
    ID      VARCHAR2(50),
    NAME    VARCHAR2(50),
    FOREIGN KEY (ID, NAME) REFERENCES TEST_COMPOSIT_PK (ID, NAME),
    PRIMARY KEY (PID, ID, NAME)
);

INSERT INTO TEST_COMPOSIT_FK VALUES ('P001', 'RUBY', '녕');

SELECT  *
FROM    TEST_COMPOSIT_FK ;

DROP TABLE TEST_COMPOSIT_FK;

--두개의 부모테이블을 갖는 자식테이블
CREATE TABLE    TEST_S1(
    SID     VARCHAR(50) PRIMARY KEY,
    PHONE   NUMBER
);

INSERT INTO TEST_S1 VALUES('RUBY', 12341234);
INSERT INTO TEST_S1 VALUES('DIA', 11112222);

SELECT  *
FROM    TEST_S1;

DROP TABLE  TEST_S1;
 ------------------------------------------------------------
CREATE TABLE    TEST_S2(
    TID     VARCHAR(50) PRIMARY KEY,
    NAME    VARCHAR(50) DEFAULT 'DEFAULT'
);

INSERT INTO TEST_S2 VALUES ('FRUIT', 'CHERRY');
INSERT INTO TEST_S2 VALUES ('ANIMAL', 'RABBIT');

SELECT *
FROM    TEST_S2;

DROP TABLE TEST_S2;
--------------------------------------------------------------
CREATE TABLE    TEST_CHILD(
    CID     VARCHAR(50) PRIMARY KEY,
    SID     VARCHAR(50) REFERENCES TEST_S1(SID),
    TID     VARCHAR(50) REFERENCES TEST_S2(TID)
);

INSERT INTO TEST_CHILD VALUES ('녕', 'RUBY', 'FRUIT');
INSERT INTO TEST_CHILD VALUES ('은영', 'DIA', 'ANIMAL');

SELECT  *
FROM    TEST_CHILD;

DROP TABLE TEST_CHILD;















